INSERT INTO customer (id, name, email) VALUES
(1, 'Aline Silva', 'aline_silva@email.com'),
(2, 'Mariazinha-2', 'mariazinha@email.com'),
(3, 'Mariazinha-3', 'mariazinha@email.com'),
(4, 'Mariazinha-4', 'mariazinha@email.com'),
(5, 'Mariazinha-5', 'mariazinha@email.com'),
(6, 'Mariazinha-6', 'mariazinha@email.com'),
(7, 'Mariazinha-7', 'mariazinha@email.com'),
(8, 'Mariazinha-8', 'mariazinha@email.com'),
(9, 'Mariazinha-9', 'mariazinha@email.com'),
(10, 'Joãozinho-10', 'joaozinho@email.com'),
(11, 'Joãozinho-11', 'joaozinho@email.com'),
(12, 'Joãozinho-12', 'joaozinho@email.com'),
(13, 'Joãozinho-13', 'joaozinho@email.com'),
(14, 'Joãozinho-14', 'joaozinho@email.com'),
(15, 'Joãozinho-15', 'joaozinho@email.com'),
(16, 'Joãozinho-16', 'joaozinho@email.com'),
(17, 'Joãozinho-17', 'joaozinho@email.com'),
(18, 'Joãozinho-18', 'joaozinho@email.com'),
(19, 'Joãozinho-19', 'joaozinho@email.com'),
(20, 'Joãozinho-20', 'joaozinho@email.com'),
(21, 'Joãozinho-21', 'joaozinho@email.com'),
(22, 'Joãozinho-22', 'joaozinho@email.com'),
(23, 'Joãozinho-23', 'joaozinho@email.com');